### ISSUE TITLE
Support ESM by upgrading @opentelemetry/instrumentation dependency

### ISSUE THREAD

**Issue by lovre-nc** [appsignal/opentelemetry-instrumentation-bullmq#8]
Hi! First of all, thank you for providing this package.

We're using ESM and the instrumentation doesn't work. 
I suspect that is because @opentelemetry/instrumentation added ESM support only in v0.40.0 (https://github.com/open-telemetry/opentelemetry-js/releases/tag/experimental%2Fv0.40.0).

Our solution is overriding the version using a pnpm feature:
```json
  "pnpm": {
    "overrides": {
      "@appsignal/opentelemetry-instrumentation-bullmq>@opentelemetry/instrumentation": "^0.52.1"
    }
  }
```

It seems to work fine with the override but it would be nice if it ESM was supported out of the box.

**Comment by unflxw** [comment]
Hi @lovre-nc, thank you for reporting this, and apologies for the delay in getting back to you and addressing this issue.

I have just released `@appsignal/opentelemetry-instrumentation-bullmq@0.7.2`, which bumps the dependency in `@opentelemetry/instrumentation` to `^0.52.1`.

Please give it a try and let us know whether this fixes the issue.

**Comment by lovre-nc** [comment]
Thank you, that fixed it.
